baseURL = "http://code.deqiang.wang/"
title = "Code is poetry."
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
pygmentsstyle = "fruity"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "code-rmsprdt3mn"
    
[params]
  author = "Francis"
  info = "Stay focused, be present"
  description = "Francis' code gists"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.png"
  #gravatar = "doe@example.com"

  favicon_32 = "images/avatar32.png"
  favicon_16 = "images/avatar16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/idealdestructor/"
[[params.social]]
  name = "Instagram"
  icon = "fa fa-instagram fa-2x"
  weight = 2
  url = "https://instagram.com/idealdestructor/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/idealdestructor/"

# Menu links
[[menu.main]]
  name = "Posts"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"